import React, { useState, useCallback } from 'react';
import { DamlLedger, useParty, useLedger, useStreamQueries, CreateEvent } from '@c7/react';
import './App.css';

// --- Type Definitions ---
// In a real project, these would be generated by `dpm codegen-js` or a similar tool.
// They are defined here manually for demonstration purposes.

type Party = string;
type ContractId<T> = string;
type Decimal = string;
type Date = string; // YYYY-MM-DD

interface TradeContract {
  tradeId: string;
  clearingHouse: Party;
  partyA: Party;
  partyB: Party;
  notional: Decimal;
  currency: string;
  effectiveDate: Date;
  maturityDate: Date;
  mtm: Decimal;
}

interface VariationMarginCall {
  tradeCid: ContractId<TradeContract>;
  clearingHouse: Party;
  clearingMember: Party;
  callAmount: Decimal;
  dueDate: Date;
}

interface TradeProposal {
  clearingHouse: Party;
  partyA: Party; // Proposer
  partyB: Party; // Counterparty
  tradeId: string;
  notional: Decimal;
  currency: string;
  effectiveDate: Date;
  maturityDate: Date;
}

// --- Constants ---

const LEDGER_URL = 'http://localhost:7575';
const TRADE_PROPOSAL_TEMPLATE = 'Trade:TradeProposal';
const TRADE_CONTRACT_TEMPLATE = 'Trade:TradeContract';
const VM_CALL_TEMPLATE = 'Margin:VariationMarginCall';
// In a real app, the Clearing House party would be discovered from a role contract.
const CLEARING_HOUSE_PARTY = 'ClearingHouse::12202b8f87f2e6f5127050cb3298a5879f5367d30f555d49215007b8a7f766e481c7';

// --- Main App Component ---

const App: React.FC = () => {
  const [token, setToken] = useState<string | null>(localStorage.getItem('daml.token'));

  if (!token) {
    return <LoginScreen onLogin={(newToken) => {
      localStorage.setItem('daml.token', newToken);
      setToken(newToken);
    }} />;
  }

  return (
    <DamlLedger token={token} party="" url={LEDGER_URL}>
      <MainScreen />
    </DamlLedger>
  );
};

// --- Screens and Components ---

const LoginScreen: React.FC<{ onLogin: (token: string) => void }> = ({ onLogin }) => {
  const [token, setToken] = useState('');

  const handleLogin = () => {
    if (token.trim() !== '') {
      onLogin(token);
    }
  };

  return (
    <div className="login-container">
      <div className="login-box">
        <h2>Derivatives Clearing Portal</h2>
        <p>Enter your user JWT token to connect to the Canton ledger.</p>
        <input
          type="password"
          placeholder="User JWT Token"
          value={token}
          onChange={(e) => setToken(e.target.value)}
          onKeyDown={(e) => e.key === 'Enter' && handleLogin()}
        />
        <button onClick={handleLogin}>Login</button>
      </div>
    </div>
  );
};

const MainScreen: React.FC = () => {
  const party = useParty();
  const ledger = useLedger();
  const { contracts: trades, loading: tradesLoading } = useStreamQueries(TRADE_CONTRACT_TEMPLATE);
  const { contracts: vmCalls, loading: vmCallsLoading } = useStreamQueries(VM_CALL_TEMPLATE);
  const { contracts: proposals, loading: proposalsLoading } = useStreamQueries(TRADE_PROPOSAL_TEMPLATE);

  const [showNewTradeModal, setShowNewTradeModal] = useState(false);

  const incomingProposals = proposals.filter(p => p.payload.partyB === party);

  const handleSettleMargin = useCallback(async (vmCall: CreateEvent<VariationMarginCall>) => {
    try {
      await ledger.exercise(VM_CALL_TEMPLATE, vmCall.contractId, 'SettleMargin', {});
      alert(`Margin call for ${vmCall.payload.callAmount} settled successfully.`);
    } catch (error) {
      console.error("Failed to settle margin:", error);
      alert(`Error settling margin: ${(error as Error).message}`);
    }
  }, [ledger]);

  const handleAcceptProposal = useCallback(async (proposal: CreateEvent<TradeProposal>) => {
    try {
      await ledger.exercise(TRADE_PROPOSAL_TEMPLATE, proposal.contractId, 'AcceptTrade', {});
      alert(`Trade proposal ${proposal.payload.tradeId} accepted.`);
    } catch (error) {
      console.error("Failed to accept proposal:", error);
      alert(`Error accepting proposal: ${(error as Error).message}`);
    }
  }, [ledger]);

  return (
    <div className="main-screen">
      <Header />
      <div className="content">
        {incomingProposals.length > 0 &&
          <div className="panel proposals-panel">
            <div className="panel-header">
              <h2>Incoming Trade Proposals</h2>
            </div>
            {proposalsLoading ? <p>Loading...</p> : <ProposalList proposals={incomingProposals} onAccept={handleAcceptProposal} />}
          </div>
        }
        <div className="panel">
          <div className="panel-header">
            <h2>Active Trades</h2>
            <button onClick={() => setShowNewTradeModal(true)}>+ Propose New Trade</button>
          </div>
          {tradesLoading ? <p>Loading trades...</p> : <TradeList trades={trades} />}
        </div>
        <div className="panel">
          <div className="panel-header">
            <h2>Open Margin Calls</h2>
          </div>
          {vmCallsLoading ? <p>Loading margin calls...</p> : <MarginCallList vmCalls={vmCalls} onSettle={handleSettleMargin} />}
        </div>
      </div>
      {showNewTradeModal &&
        <NewTradeModal
          onClose={() => setShowNewTradeModal(false)}
        />
      }
    </div>
  );
};

const Header: React.FC = () => {
  const party = useParty();

  const handleLogout = () => {
    localStorage.removeItem('daml.token');
    window.location.reload();
  };

  return (
    <header className="header">
      <h1>Canton Derivatives Clearing</h1>
      <div className="user-info">
        <span>Welcome, <strong>{party}</strong></span>
        <button onClick={handleLogout}>Logout</button>
      </div>
    </header>
  );
};

const ProposalList: React.FC<{ proposals: readonly CreateEvent<TradeProposal>[], onAccept: (c: CreateEvent<TradeProposal>) => void }> = ({ proposals, onAccept }) => (
  <table className="data-table">
    <thead>
      <tr>
        <th>From</th>
        <th>Notional</th>
        <th>Maturity</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      {proposals.map(p => (
        <tr key={p.contractId}>
          <td title={p.payload.partyA}>{p.payload.partyA.slice(0, 10)}...</td>
          <td>{parseFloat(p.payload.notional).toLocaleString()} {p.payload.currency}</td>
          <td>{p.payload.maturityDate}</td>
          <td><button onClick={() => onAccept(p)}>Accept</button></td>
        </tr>
      ))}
    </tbody>
  </table>
);

const TradeList: React.FC<{ trades: readonly CreateEvent<TradeContract>[] }> = ({ trades }) => {
  const party = useParty();
  if (trades.length === 0) return <p>No active trades found.</p>;

  return (
    <table className="data-table">
      <thead>
        <tr>
          <th>Trade ID</th>
          <th>Counterparty</th>
          <th>Notional</th>
          <th>Maturity</th>
          <th>MTM</th>
        </tr>
      </thead>
      <tbody>
        {trades.map(t => {
          const counterparty = t.payload.partyA === party ? t.payload.partyB : t.payload.partyA;
          return (
            <tr key={t.contractId}>
              <td>{t.payload.tradeId}</td>
              <td title={counterparty}>{counterparty.slice(0, 10)}...</td>
              <td>{parseFloat(t.payload.notional).toLocaleString()} {t.payload.currency}</td>
              <td>{t.payload.maturityDate}</td>
              <td className={parseFloat(t.payload.mtm) >= 0 ? 'positive' : 'negative'}>
                {parseFloat(t.payload.mtm).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
              </td>
            </tr>
          )
        })}
      </tbody>
    </table>
  );
};

const MarginCallList: React.FC<{ vmCalls: readonly CreateEvent<VariationMarginCall>[], onSettle: (c: CreateEvent<VariationMarginCall>) => void }> = ({ vmCalls, onSettle }) => {
  if (vmCalls.length === 0) return <p>No open margin calls.</p>;

  return (
    <table className="data-table">
      <thead>
        <tr>
          <th>Amount</th>
          <th>Due Date</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        {vmCalls.map(call => {
          const isPayable = parseFloat(call.payload.callAmount) > 0;
          return (
            <tr key={call.contractId}>
              <td className={isPayable ? 'negative' : 'positive'}>
                {parseFloat(call.payload.callAmount).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
              </td>
              <td>{call.payload.dueDate}</td>
              <td>
                {isPayable ? <button onClick={() => onSettle(call)}>Settle Payment</button> : <span>Awaiting Receipt</span>}
              </td>
            </tr>
          );
        })}
      </tbody>
    </table>
  );
};

const NewTradeModal: React.FC<{ onClose: () => void }> = ({ onClose }) => {
    const party = useParty();
    const ledger = useLedger();
    const [partyB, setPartyB] = useState('');
    const [notional, setNotional] = useState('10000000.0');
    const [maturityDate, setMaturityDate] = useState(new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString().split('T')[0]);

    const handleProposeTrade = useCallback(async (e: React.FormEvent) => {
      e.preventDefault();
      try {
        const payload: TradeProposal = {
            clearingHouse: CLEARING_HOUSE_PARTY,
            partyA: party,
            partyB,
            tradeId: `T-${Date.now()}`,
            notional,
            currency: "USD",
            effectiveDate: new Date().toISOString().split('T')[0],
            maturityDate
        };
        await ledger.create(TRADE_PROPOSAL_TEMPLATE, payload);
        alert('Trade proposal sent!');
        onClose();
      } catch (error) {
        console.error("Failed to propose trade:", error);
        alert(`Error proposing trade: ${(error as Error).message}`);
      }
    }, [ledger, party, partyB, notional, maturityDate, onClose]);

    return (
        <div className="modal-backdrop" onClick={onClose}>
            <div className="modal" onClick={e => e.stopPropagation()}>
                <h2>Propose New Derivative Trade</h2>
                <form onSubmit={handleProposeTrade}>
                    <label>Counterparty Party ID</label>
                    <input type="text" value={partyB} onChange={e => setPartyB(e.target.value)} required autoFocus/>

                    <label>Notional Amount (USD)</label>
                    <input type="number" step="1000" value={notional} onChange={e => setNotional(e.target.value)} required />

                    <label>Maturity Date</label>
                    <input type="date" value={maturityDate} onChange={e => setMaturityDate(e.target.value)} required />

                    <div className="modal-actions">
                        <button type="button" onClick={onClose}>Cancel</button>
                        <button type="submit">Propose Trade</button>
                    </div>
                </form>
            </div>
        </div>
    );
};

export default App;