/**
 * @module clearingService
 * @description
 * This module provides a service layer for interacting with the Daml ledger
 * for the derivatives clearing application. It encapsulates the JSON API calls
 * for creating contracts and exercising choices related to trade lifecycle,
 * margin management, and default handling.
 *
 * It provides functions for:
 * - Proposing and accepting trades.
 * - Posting initial margin.
 * - Settling variation margin calls.
 * - Requesting trade novation and expiry.
 * - Declaring defaults.
 *
 * It also exports template ID constants for use with @c7/react's query hooks.
 */

import { ContractId, Party } from '@c7/ledger';

// --- Configuration ---

// In a real application, this would come from an environment variable.
const JSON_API_URL = process.env.REACT_APP_JSON_API_URL || 'http://localhost:7575';

// --- Type Definitions ---
// These types mirror the Daml data types and would ideally be generated by
// `dpm codegen-js` for type safety.

/** Details of a bilateral derivative trade. */
export type TradeDetails = {
  tradeId: string;
  counterpartyA: Party;
  counterpartyB: Party;
  clearingHouse: Party;
  notionalAmount: string; // Daml Decimal
  currency: string;
  underlyingAsset: string;
  maturityDate: string; // Daml Date (YYYY-MM-DD)
  initialMarginA: string; // Daml Decimal
  initialMarginB: string; // Daml Decimal
};

/** Represents a pending trade proposal from one party to another. */
export interface TradeProposal {
  proposer: Party;
  accepter: Party;
  details: TradeDetails;
}

/** Represents an agreed-upon trade, linked to a margin account. */
export interface TradeAgreement {
  details: TradeDetails;
  marginAccountCid: ContractId<MarginAccount>;
}

/** Represents the margin account for a single trade, held at the clearing house. */
export interface MarginAccount {
  clearingHouse: Party;
  partyA: Party;
  partyB: Party;
  tradeId: string;
  balanceA: string; // Daml Decimal
  balanceB: string; // Daml Decimal
  status: "Active" | "Defaulted" | "Closed";
}

/** A call for one party to pay variation margin to another. */
export interface VariationMarginCall {
  clearingHouse: Party;
  payer: Party;
  receiver: Party;
  tradeId: string;
  amount: string; // Daml Decimal
  dueDate: string; // Daml Date (YYYY-MM-DD)
}

// --- API Helper ---

/**
 * A generic helper function to make POST requests to the JSON API.
 * @param token The JWT for ledger authentication.
 * @param endpoint The API endpoint (e.g., '/v1/create').
 * @param body The request body.
 * @returns The JSON response from the API.
 * @throws An error if the network request fails or the API returns a non-OK status.
 */
const apiFetch = async <T>(token: string, endpoint: string, body: object): Promise<T> => {
  const response = await fetch(`${JSON_API_URL}${endpoint}`, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(body),
  });

  if (!response.ok) {
    const errorBody = await response.text();
    const errorMessage = `JSON API request to ${endpoint} failed with status ${response.status}: ${errorBody}`;
    console.error(errorMessage);
    throw new Error(errorMessage);
  }
  return response.json();
};

// --- Service Functions for Commands ---

/**
 * Creates a new TradeProposal contract on the ledger.
 * @param token The JWT token for authentication.
 * @param payload The payload for creating the TradeProposal contract.
 */
export const proposeTrade = async (token: string, payload: TradeProposal) => {
  return apiFetch(token, '/v1/create', {
    templateId: 'Canton.Derivatives.Trade:TradeProposal',
    payload,
  });
};

/**
 * Exercises the `AcceptTrade` choice on a `TradeProposal` contract.
 * @param token The JWT token for authentication.
 * @param proposalCid The ContractId of the `TradeProposal` to accept.
 */
export const acceptTrade = async (token: string, proposalCid: ContractId<TradeProposal>) => {
  return apiFetch(token, '/v1/exercise', {
    templateId: 'Canton.Derivatives.Trade:TradeProposal',
    contractId: proposalCid,
    choice: 'AcceptTrade',
    argument: {},
  });
};

/**
 * Exercises the `PostInitialMargin` choice on a `MarginAccount` contract.
 * @param token The JWT token for authentication.
 * @param marginAccountCid The ContractId of the `MarginAccount`.
 * @param postingParty The party posting the margin.
 * @param amount The amount of initial margin to post.
 */
export const postInitialMargin = async (
  token: string,
  marginAccountCid: ContractId<MarginAccount>,
  postingParty: Party,
  amount: string
) => {
  return apiFetch(token, '/v1/exercise', {
    templateId: 'Canton.Derivatives.Clearing:MarginAccount',
    contractId: marginAccountCid,
    choice: 'PostInitialMargin',
    argument: { postingParty, amount },
  });
};

/**
 * Exercises the `SettleVariationMargin` choice on a `VariationMarginCall` contract.
 * @param token The JWT token for authentication.
 * @param marginCallCid The ContractId of the `VariationMarginCall`.
 */
export const settleVariationMargin = async (token: string, marginCallCid: ContractId<VariationMarginCall>) => {
  return apiFetch(token, '/v1/exercise', {
    templateId: 'Canton.Derivatives.Clearing:VariationMarginCall',
    contractId: marginCallCid,
    choice: 'SettleVariationMargin',
    argument: {},
  });
};

/**
 * Exercises the `DeclareDefault` choice on a `MarginAccount`, initiating the default management waterfall.
 * @param token The JWT token for authentication.
 * @param marginAccountCid The ContractId of the associated `MarginAccount`.
 * @param defaultedParty The party being declared in default.
 */
export const declareDefault = async (
  token: string,
  marginAccountCid: ContractId<MarginAccount>,
  defaultedParty: Party
) => {
    return apiFetch(token, '/v1/exercise', {
        templateId: 'Canton.Derivatives.Clearing:MarginAccount',
        contractId: marginAccountCid,
        choice: 'DeclareDefault',
        argument: { defaultedParty },
    });
};

/**
 * Exercises the `ExpireTrade` choice on a `TradeAgreement`. This is typically automated
 * but can be exposed in the UI for manual intervention.
 * @param token The JWT token for authentication.
 * @param tradeCid The ContractId of the `TradeAgreement` to expire.
 */
export const expireTrade = async (token: string, tradeCid: ContractId<TradeAgreement>) => {
  return apiFetch(token, '/v1/exercise', {
    templateId: 'Canton.Derivatives.Trade:TradeAgreement',
    contractId: tradeCid,
    choice: 'ExpireTrade',
    argument: {},
  });
};

// --- Template ID Constants for Queries ---
// Exported for use with @c7/react's useStreamQueries and useQuery hooks.

export const TradeProposalTemplateId = 'Canton.Derivatives.Trade:TradeProposal';
export const TradeAgreementTemplateId = 'Canton.Derivatives.Trade:TradeAgreement';
export const MarginAccountTemplateId = 'Canton.Derivatives.Clearing:MarginAccount';
export const VariationMarginCallTemplateId = 'Canton.Derivatives.Clearing:VariationMarginCall';
export const DefaultFundContributionTemplateId = 'Canton.Derivatives.DefaultManagement:DefaultFundContribution';
export const ClearingMemberRoleTemplateId = 'Canton.Derivatives.Role:ClearingMemberRole';