#!/bin/bash
#
# Description:
#   Allocates the central Clearinghouse party on the Canton sandbox ledger
#   and creates its associated ClearinghouseRole contract. This script is
#   idempotent and can be run multiple times safely.
#
#   The script performs the following actions:
#   1. Checks if a party with the display name "Clearinghouse" already exists.
#   2. If not, it allocates a new party using the JSON API.
#   3. Generates a JWT for the Clearinghouse party.
#   4. Checks if a ClearinghouseRole contract for this party already exists.
#   5. If not, it creates one using the JSON API.
#   6. Writes the party ID and JWT to a `.env` file for use by other scripts
#      and the frontend application.
#
# Usage:
#   ./scripts/setup-clearinghouse.sh
#

set -euo pipefail

# --- Configuration ---
JSON_API_URL="http://localhost:7575"
LEDGER_ID="sandbox" # Default for `dpm sandbox`
APP_ID="canton-derivatives-clearing"
PARTY_DISPLAY_NAME="Clearinghouse"
PARTY_ID_HINT="Clearinghouse"
# This assumes a role contract exists with this template ID in your Daml models.
# e.g., in Clearing/Role.daml: `template ClearinghouseRole with clearinghouse: Party where signatory clearinghouse`
ROLE_TEMPLATE_ID="Clearing.Role:ClearinghouseRole"
ENV_FILE="clearinghouse.env"

# --- Helper Functions ---
function check_deps() {
  local missing=0
  for dep in curl jq; do
    if ! command -v "$dep" &> /dev/null; then
      echo "ERROR: Required command '$dep' is not installed."
      missing=1
    fi
  done
  if [ "$missing" -eq 1 ]; then
    echo "Please install the missing dependencies and try again."
    exit 1
  fi
}

# --- Main Script ---
check_deps

echo "▶️  Setting up Clearinghouse party on ledger at $JSON_API_URL..."

# 1. Find or allocate the Clearinghouse party
echo "🔎 Checking for existing '$PARTY_DISPLAY_NAME' party..."
ALL_PARTIES_JSON=$(curl -s -X GET "$JSON_API_URL/v1/parties")
PARTY_ID=$(echo "$ALL_PARTIES_JSON" | jq -r ".result[] | select(.displayName == \"$PARTY_DISPLAY_NAME\") | .identifier")

if [[ -z "$PARTY_ID" ]]; then
  echo "🟡 Party not found. Allocating a new party..."
  ALLOCATE_RESPONSE=$(curl -s -X POST "$JSON_API_URL/v2/parties/allocate" \
    -H "Content-Type: application/json" \
    -d "{
      \"identifier_hint\": \"$PARTY_ID_HINT\",
      \"display_name\": \"$PARTY_DISPLAY_NAME\"
    }")

  PARTY_ID=$(echo "$ALLOCATE_RESPONSE" | jq -r ".party_details.identifier")

  if [[ -z "$PARTY_ID" || "$PARTY_ID" == "null" ]]; then
    echo "❌ ERROR: Failed to allocate party. Response:"
    echo "$ALLOCATE_RESPONSE"
    exit 1
  fi
  echo "✅ Party '$PARTY_DISPLAY_NAME' allocated with ID: $PARTY_ID"
else
  echo "✅ Found existing party with ID: $PARTY_ID"
fi

# 2. Generate a JWT for the party
# For Canton sandbox, a simple base64-encoded payload is sufficient.
HEADER='{"alg": "HS256", "typ": "JWT"}'
PAYLOAD="{\"ledgerId\": \"$LEDGER_ID\", \"applicationId\": \"$APP_ID\", \"actAs\": [\"$PARTY_ID\"]}"

# Use a portable way to base64 encode for both Linux and macOS
if command -v "base64" &>/dev/null && [[ "$(uname)" == "Linux" ]]; then
  # Linux `base64` uses -w 0 to disable line wrapping
  HEADER_B64=$(echo -n "$HEADER" | base64 -w 0)
  PAYLOAD_B64=$(echo -n "$PAYLOAD" | base64 -w 0)
elif command -v "openssl" &>/dev/null; then
  # macOS `base64` doesn't have -w 0, but `openssl` is a reliable fallback
  HEADER_B64=$(echo -n "$HEADER" | openssl base64 -e -A)
  PAYLOAD_B64=$(echo -n "$PAYLOAD" | openssl base64 -e -A)
else
  echo "❌ ERROR: Could not find a base64 encoder ('base64 -w 0' or 'openssl')."
  exit 1
fi

JWT="$HEADER_B64.$PAYLOAD_B64."
echo "🔑 Generated JWT for party."

# 3. Create the ClearinghouseRole contract if it doesn't exist
echo "🔎 Checking for existing '$ROLE_TEMPLATE_ID' contract..."

QUERY_RESPONSE=$(curl -s -X POST "$JSON_API_URL/v1/query" \
  -H "Authorization: Bearer $JWT" \
  -H "Content-Type: application/json" \
  -d "{\"templateIds\": [\"$ROLE_TEMPLATE_ID\"]}")

EXISTING_CONTRACTS=$(echo "$QUERY_RESPONSE" | jq -r '.result | length')

if [[ "$EXISTING_CONTRACTS" -eq 0 ]]; then
  echo "🟡 Role contract not found. Creating one..."
  CREATE_RESPONSE=$(curl -s -w '%{http_code}' -o /dev/null -X POST "$JSON_API_URL/v1/create" \
    -H "Authorization: Bearer $JWT" \
    -H "Content-Type: application/json" \
    -d "{
      \"templateId\": \"$ROLE_TEMPLATE_ID\",
      \"payload\": {
        \"clearinghouse\": \"$PARTY_ID\"
      }
    }")

  if [[ "$CREATE_RESPONSE" != "200" ]]; then
      echo "❌ ERROR: Failed to create ClearinghouseRole contract. HTTP Status: $CREATE_RESPONSE"
      exit 1
  fi
  echo "✅ Role contract created successfully."
else
  echo "✅ Role contract already exists."
fi

# 4. Write credentials to .env file
echo "💾 Writing credentials to '$ENV_FILE'..."
cat > "$ENV_FILE" << EOL
# Credentials for the Clearinghouse party on the local Canton sandbox
# Generated by scripts/setup-clearinghouse.sh on $(date)

# The unique identifier for the Clearinghouse party
export CLEARINGHOUSE_PARTY_ID="$PARTY_ID"

# A JSON Web Token (JWT) that grants access to act as the Clearinghouse party
export CLEARINGHOUSE_JWT="$JWT"
EOL

echo ""
echo "🎉 Setup complete! You can now use '$ENV_FILE' to configure your application."
echo "   Run 'source $ENV_FILE' to load the variables into your shell."